services:
  - type: web
    name: battlesnake-hardml-ensemble
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 30
    envVars:
      - key: BATTLE_MODEL
        value: ensemble
